version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: u3097435_default
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: .
    container_name: backend_app
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:password@db:3306/u3097435_default
      WHOISXMLAPI_API_KEY: at_RuBLKZoDoKwmVlE8qzIWKpCDpdJYD
      BOT_TOKEN: 7718998375:AAGwfHH7y7jY1Bq-zs_x2ociWsRYZY3k7Ok
    ports:
      - "3000:3000"
    command: ["sh", "-c", "./wait-for-it.sh db:3306 -- npx prisma migrate deploy && npm run start:prod"]

volumes:
  mysql-data:
